# web服务的端口
server:
  port: 8080
langchain4j:
  open-ai:
    chat-model:
      base_url: 改成你自己的baseurl
      api-key: 改成你自己的apikey
      model-name: deepseek-r1  
      #应用程序发生给大模型的请求日志和响应日志
      log-requests: true
      log-responses: true
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: deepseek-r1:1.5b
      temperature: 0.8
      timeout: PT60S
      log-requests: true
      log-responses: true
  community:
    dashscope:
      chat-model:
        api-key: 改成你自己的apikey
        model-name: qwen-max
      embedding-model:
        api-key: 改成你自己的apikey
        model-name: text-embedding-v3
      #流式输出
      streaming-chat-model:
        api-key: 改成你自己的apikey
        model-name: qwen-plus

#设置系统的日志级别
logging:
  level:
    root: info

spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 2GB
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db
    redis:
      port: 6379
      host: localhost
      password: 改成你自己的pwd
      database: 1


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/改成你自己的db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 改成你自己的pwd




